Repository JuliaLang/juliaup, pull requests merged in 2022-11, with the labels that each got.

#447 Go back to ~/.juliaup as the default install location
  src/bin/juliainstaller.rs
Labels: enhancement

#488 Document releasepreview usage
  README.md
Labels: documentation

#483 Enable ci tests of musl build
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: bug, help wanted

#496 Configure for target_os, not nonexistant family
  Cargo.toml
  src/operations.rs
Labels: bug
